name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Zip code
              run: |
                    cd dev
                    zip code.zip lambda.py

            - name: Deploy Lambda
              uses: actions/aws/cli@v1
              with:
                  args: lambda update-function-code --function-name crud --zip-file fileb://dev/code.zip
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: us-west-1