name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Zip code
              run: |
                    cd dev
                    zip code.zip lambda.py

            - name: Deploy Lambda
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-region: us-west-1


            - name: Upload code
              run: aws lambda update-function-code --function-name crud --zip-file fileb://dev/code.zip